### ISSUE TITLE
Roadmap: Finishing the first version of RFC for editorial review

### ISSUE THREAD

**Issue by mbakholdina** [Haivision/srt-rfc#40]
- [x] Estimate an effort required to finish the first version of RFC

ToDo:
- [x] Review the suggestions by Joonwoong (Maxim),
- [ ] Congestion Control section (~ 3-5 days, Maria),
        - SRT provides mechanisms for CC (ARQ, ACK, statistics),
        - Any CC algorithm may be integrated as a separate module,
        - The main idea of the currently used CC algorithm without giving too much details,
        - Briefly about the modification done on top of UDT CC.
- [ ] Encryption section (Justin, Maxim),
       - https://github.com/Haivision/srt-rfc/pull/41 
       - #47
- [ ] Learn more about possible conflict of interests with regards to IETF vs SRT community IPR policy (Maria),
- [ ] Submit RFC for the editorial review (Joonwoong)

For the second iteration (create a separate task for this):
- Review and improve handshakes section,
- Review and improve acknowledgements section

**Comment by mbakholdina** [comment]
Duplicate of #49. Closing.
